FROM nginx
RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY content /usr/share/nginx/html
COPY conf /etc/nginx
COPY conf/Dockerfile /var/lib/docker/tmp/buildkit-mount171998907/Dockerfile
