pipeline:
  identifier: Build_nginx_1693812082548
  name: Build nginx
  orgIdentifier: default
  projectIdentifier: Project1
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1693812039869
        repoName: vishalvaidya269/nginx
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: echo
                      name: echo
                      spec:
                        command: echo hello world
                      timeout: ""
                      type: Run
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry_1
                      identifier: BuildAndPushDockerRegistry_1
                      spec:
                        connectorRef: account.harnessImage
                        repo: vaidyavishal269
                        tags:
                          - buildimage
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
